# buildspec.yml for Project Phoenix
# DEFINITIVE MIGRATION VERSION: Pushes to both eu-west-1 and eu-west-2.

version: 0.2

env:
  variables:
    ACCOUNT_ID: "537124950121"
    PRIMARY_REGION: "eu-west-2"
    SECONDARY_REGION: "eu-west-1"
    IMAGE_REPO_NAME: "mamba-rl-trading"
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - 'echo "Logging in to ECR in both regions..."'
      - aws ecr get-login-password --region $PRIMARY_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$PRIMARY_REGION.amazonaws.com
      - aws ecr get-login-password --region $SECONDARY_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$SECONDARY_REGION.amazonaws.com

  build:
    commands:
      - 'echo "Build started on $(date)"'
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - 'echo "Build completed on $(date)"'
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - 'echo "Tagging and Pushing to Primary Region (eu-west-2)..."'
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$PRIMARY_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$PRIMARY_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push --all-tags $ACCOUNT_ID.dkr.ecr.$PRIMARY_REGION.amazonaws.com/$IMAGE_REPO_NAME
      
      - 'echo "Tagging and Pushing to Secondary Region (eu-west-1)..."'
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$SECONDARY_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$SECONDARY_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push --all-tags $ACCOUNT_ID.dkr.ecr.$SECONDARY_REGION.amazonaws.com/$IMAGE_REPO_NAME
