# buildspec.yml for Project Phoenix
# DEFINITIVE FINAL VERSION: Adds a clock sync command to prevent exit status 254.

version: 0.2

runtime-versions:
  python: 3.10

phases:
  install:
    commands:
      # <<< THE FIX IS HERE: Install network time tools and sync the clock >>>
      - 'echo "Installing ntpdate to sync clock..."'
      - apt-get update -y
      - apt-get install -y ntpdate
      - 'echo "Forcing clock sync to fix potential skew..."'
      - ntpdate time.nist.gov

  pre_build:
    commands:
      - 'echo "Logging in to Amazon ECR (Private)..."'
      - ACCOUNT_ID=537124950121
      - REGION=eu-west-2
      - IMAGE_REPO_NAME=mamba-rl-trading
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - 'echo "Logging in to Amazon ECR (Public)..."'
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  build:
    commands:
      - 'echo "Build started on $(date)"'
      - 'echo "Building the Docker image with cache support..."'
      - docker pull $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest || true
      - docker build --cache-from $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - 'echo "Build completed on $(date)"'
      - 'echo "Pushing the Docker images to ECR..."'
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

cache:
  paths:
    - '/var/lib/docker-v2/**/*'
