version: 0.2
env:
  variables:
    ACCOUNT_ID: "537124950121"
    REGION: "eu-west-2"
    IMAGE_REPO_NAME: "mamba_rl_trading"
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin 763104351884.dkr.ecr.${REGION}.amazonaws.com
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - echo "Build started on $(date)"
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Building Docker image with tag ${IMAGE_TAG}"
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Tagging and pushing to ${REGION}"
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo "Creating image detail file"
      - printf '[{"name":"MambaRLTradingImage","imageUri":"%s"}]' "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
