# buildspec.yml for Project Phoenix
# DEFINITIVE FINAL VERSION: Works around Docker's non-TTY login bug.

version: 0.2

runtime-versions:
  python: 3.10

phases:
  pre_build:
    commands:
      - 'echo "Logging in to Amazon ECR (Private)..."'
      - ACCOUNT_ID=537124950121
      - REGION=eu-west-2
      - IMAGE_REPO_NAME=mamba-rl-trading
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      
      - 'echo "Logging in to Amazon ECR (Public)..."'
      # <<< THE FIX IS HERE: Use a temporary file to avoid the pipe issue >>>
      - aws ecr-public get-login-password --region us-east-1 > ecr_public_token.txt
      - cat ecr_public_token.txt | docker login --username AWS --password-stdin public.ecr.aws
      - rm ecr_public_token.txt

  build:
    commands:
      - 'echo "Build started on $(date)"'
      - 'echo "Building the Docker image with cache support..."'
      - docker pull $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest || true
      - docker build --cache-from $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - 'echo "Build completed on $(date)"'
      - 'echo "Pushing the Docker images to ECR..."'
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

# Using the new, clean cache path permanently.
cache:
  paths:
    - '/var/lib/docker-v2/**/*'
