version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing ECR credential helper..."
      - apt-get update -y
      - apt-get install -y amazon-ecr-credential-helper

  pre_build:
    commands:
      - echo "Configuring Docker to use ECR credential helper..."
      - mkdir -p ~/.docker
      - echo '{"credsStore":"ecr-login"}' > ~/.docker/config.json
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - export IMAGE_URI=$ECR_REPOSITORY_URI:$IMAGE_TAG
      - |
        if ! aws ecr describe-repositories \
            --repository-names mamba-rl-trading \
            --region $AWS_REGION > /dev/null 2>&1; then
          echo "ERROR: ECR repository not found"
          exit 1
        fi
      - docker pull $ECR_REPOSITORY_URI:latest || echo "No previous image to pull (first build?)"

  build:
    commands:
      - echo "Building Docker image..."
      - |
        if docker inspect $ECR_REPOSITORY_URI:latest > /dev/null 2>&1; then
          echo "Using latest image as build cache"
          docker build \
            --cache-from $ECR_REPOSITORY_URI:latest \
            -t $ECR_REPOSITORY_URI:$IMAGE_TAG \
            -t $ECR_REPOSITORY_URI:latest \
            .
        else
          echo "No cached image. Building from scratch."
          docker build \
            -t $ECR_REPOSITORY_URI:$IMAGE_TAG \
            -t $ECR_REPOSITORY_URI:latest \
            .
        fi

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest
