version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - apt-get update -y
      - apt-get install -y amazon-ecr-credential-helper
  pre_build:
    commands:
      - mkdir -p ~/.docker
      - echo '{ "credsStore": "ecr-login" }' > ~/.docker/config.json
      - export ACCOUNT_ID=537124950121
      - export REGION=eu-west-2
      - export IMAGE_REPO_NAME=mamba-rl-trading
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

cache:
  paths:
    - '/var/lib/docker-v2/**/*'
