version: 0.2

env:
  variables:
    ACCOUNT_ID: "537124950121"
    REGION: "eu-west-2"
    IMAGE_REPO_NAME: "mamba_rl_trading"
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export REPO_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
      - export LATEST_IMAGE_URI="${REPO_URI}:latest"
      - export TAGGED_IMAGE_URI="${REPO_URI}:${IMAGE_TAG}"

      - echo "Pulling latest image for cache..."
      - docker pull ${LATEST_IMAGE_URI} || true

      - echo "Building Docker image with BuildKit cache..."
      - |
        docker build \
          --cache-from ${LATEST_IMAGE_URI} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t ${TAGGED_IMAGE_URI} \
          -t ${LATEST_IMAGE_URI} \
          .

      - echo "Build complete!"

  post_build:
    commands:
      - echo "Pushing tagged image (${IMAGE_TAG})..."
      - docker push ${TAGGED_IMAGE_URI}

      - echo "Pushing latest image..."
      - docker push ${LATEST_IMAGE_URI}

      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"MambaRLTradingImage","imageUri":"%s"}]' "${TAGGED_IMAGE_URI}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.cache/pip/**/*'
