version: 0.2

env:
  variables:
    ACCOUNT_ID: "537124950121"
    REGION: "eu-west-2"
    IMAGE_REPO_NAME: "mamba_rl_trading"
    # --- THIS IS THE KEY ---
    # We are telling the build to use this specific tag for our test
    IMAGE_TAG: "test-no-chrome"

phases:
  pre_build:
    commands:
      - echo "===== PRE-BUILD PHASE ====="
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin 763104351884.dkr.ecr.${REGION}.amazonaws.com
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "Building Docker image with tag ${IMAGE_TAG}"
      # --- THIS IS THE KEY ---
      # We are telling it to use the default Dockerfile (no -f flag)
      - echo "Using default Dockerfile"
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - echo "--- Verifying local images after build ---"
      - docker images | grep ${IMAGE_REPO_NAME}

  post_build:
    commands:
      - echo "===== POST-BUILD PHASE ====="
      - echo "Tagging and pushing image ${IMAGE_TAG} to ${REGION}"
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo "Creating image detail file for downstream services..."
      - printf '[{"name":"MambaRLTradingImage","imageUri":"%s"}]' "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "===== BUILD COMPLETE ====="

artifacts:
  files:
    - imagedefinitions.json
