version: 0.2

env:
  variables:
    ACCOUNT_ID: "537124950121"
    REGION: "eu-west-2"
    IMAGE_REPO_NAME: "mamba_rl_trading"
    # Enable Docker BuildKit for advanced caching
    DOCKLOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export LATEST_IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:latest"
      - echo "Building with BuildKit and layer cache..."
      - docker pull ${LATEST_IMAGE_URI} || true
      # Use a multi-line command for readability with BuildKit flags
      # This builds and tags both the commit hash and 'latest' in one step
      - |
        docker build \
          --cache-from ${LATEST_IMAGE_URI} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} \
          -t ${LATEST_IMAGE_URI} \
          .
      - echo "Build complete!"

  post_build:
    commands:
      - echo "Pushing images..."
      # The images are already tagged, so we just need to push them
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker push ${LATEST_IMAGE_URI}
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"MambaRLTradingImage","imageUri":"%s"}]' "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

# Cache pip and conda downloads between CodeBuild runs
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/opt/conda/pkgs/**/*' # Correct path for conda packages
