# buildspec.yml for Project Phoenix
# DEFINITIVE FINAL VERSION: Builds the fast app image. Caching is now implicit.

version: 0.2

env:
  variables:
    ACCOUNT_ID: "537124950121"
    REGION: "eu-west-2"
    IMAGE_REPO_NAME: "mamba-rl-trading"
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - 'echo "Logging in to ECR..."'
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - 'echo "Build started on $(date)"'
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      # This build is now very fast because the base image has everything pre-installed
      - docker build -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - 'echo "Build completed on $(date)"'
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - 'echo "Tagging and Pushing Docker images to ECR..."'
      - docker tag $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push --all-tags $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME
