# buildspec.yml for Project Phoenix
# This file provides explicit, version-controlled instructions to AWS CodeBuild.
# It includes the definitive fix for enabling persistent Docker layer caching.

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=537124950121
      - REGION=eu-west-2
      - IMAGE_REPO_NAME=mamba-rl-trading
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image with cache support...
      # The --cache-from flag explicitly tells Docker to use a potential cache
      # from a previous 'latest' image. This makes the caching more robust.
      - docker pull $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest || true
      - docker build --cache-from $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # Also tag this new build as 'latest' to be the cache source for the next run
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

# <<< THE CRITICAL FIX IS HERE >>>
# This block explicitly tells CodeBuild to cache Docker's internal storage
# directory between runs. This is the most reliable way to enable layer caching.
cache:
  paths:
    - '/var/lib/docker/**/*'
