# launch_configs.yaml
# Central configuration for all SageMaker job types.
# --- Utility & Diagnostic Jobs ---
smoke_test:
  # <<< FIXED: Using spot instances (you have quota) and extended time >>>
  instance_type: "ml.g4dn.xlarge" # GPU instance
  instance_count: 1
  volume_size_gb: 30
  use_spot: true  # <<<< CRITICAL FIX: Must use spot (you only have spot quota)
  max_run_seconds: 10800 # 3 hours - good increase from 1 hour
  base_job_name_prefix: "mamba-{{instrument}}-smoke-test"
  hydra_experiment: "smoke_test"

# --- Phase 5: PPO Baseline ---
phase5a_explore_hpo:
  instance_type: "ml.g4dn.xlarge"
  instance_count: 1
  volume_size_gb: 80
  use_spot: true
  max_run_seconds: 43200 # 12 hours
  base_job_name_prefix: "mamba-{{instrument}}-p5a-explore"
  hydra_experiment: "explore"

phase5b_refine_hpo:
  instance_type: "ml.g4dn.2xlarge"
  instance_count: 1
  volume_size_gb: 80
  use_spot: true
  max_run_seconds: 86400 # 24 hours
  base_job_name_prefix: "mamba-{{instrument}}-p5b-refine"
  hydra_experiment: "refine"

# --- Phase 6: SAC Active Trader (Placeholder) ---
phase6_sac_hpo:
  instance_type: "ml.g5.xlarge"  # <<<< FIXED: You have quota for xlarge, not 2xlarge
  instance_count: 1
  volume_size_gb: 100
  use_spot: true
  max_run_seconds: 172800 # 48 hours
  base_job_name_prefix: "mamba-{{instrument}}-p6-sac"
  hydra_experiment: "sac_hpo"

# --- Final Model Training (Example) ---
final_training:
  instance_type: "ml.g4dn.2xlarge"
  instance_count: 1
  volume_size_gb: 80
  use_spot: true  # <<<< CHANGED: Must use spot (no on-demand quota)
  max_run_seconds: 86400 # 24 hours
  base_job_name_prefix: "mamba-{{instrument}}-final-train"
  hydra_experiment: "final_train"
